#! /bin/bash

################################################################################
#                                                                              #
#                       Simple weekly Backup Script                            #
#                                                                              #
################################################################################

#---------------------------- Read Conf File ---------------------------------#
source /etc/backup/backup.conf

#----------------------------- Backup Name -----------------------------------#
BACKUP_THIS_YEAR=Yearly-$($DATE -d "yesterday" +%Y);
BACKUP_YESTERDAY=*$($DATE -d "yesterday" +%A);

#---------------------------- Body of Script ---------------------------------#

# Ensure user is root
if (( `$ID -u` != 0 )); then
    $ECHO "$0 must be run as root.";
    exit;
fi;

# Create directory for backup
$MKDIR $MOUNT_POINT/$BACKUP_THIS_YEAR ;

# Make a hard-link to the last day of the year's backup, if one exists
# If no backup for the last day of the year  exists, rsync the system
# to this year's backup
if [ -d $MOUNT_POINT/$BACKUP_YESTERDAY ] ; then
    $CP -al $MOUNT_POINT/$BACKUP_YESTERDAY/* $MOUNT_POINT/$BACKUP_THIS_YEAR ;
else
    for i in $FILE_SYSTEMS
    do
        $RSYNC                                       \
            -xav --delete                            \
            $i $MOUNT_POINT/$BACKUP_THIS_YEAR ;
    done
fi;
