#! /bin/bash

################################################################################
#                                                                              #
#                      Simple Backup and Archive Script                        #
#                                                                              #
################################################################################

#---------------------------- Read Conf File ---------------------------------#
source /etc/backup/backup.conf

#----------------------------- Backup Name -----------------------------------#
if [ $1 ]; then
    BACKUP_NAME=$1;
else
    BACKUP_NAME=Backup-$($DATE +%y%m%d);
fi;

#---------------------------- Body of Script ---------------------------------#

# Ensure user is root
if (( `$ID -u` != 0 )); then
    $ECHO "$0 must be run as root.";
    exit;
fi;

# Create directory for backup
$MKDIR $MOUNT_POINT/$BACKUP_NAME ;

# rsync the system to the backup
for i in $FILE_SYSTEMS
do
$RSYNC                                       \
    -xav --delete                            \
    $i $MOUNT_POINT/$BACKUP_NAME ;
done
