#! /bin/bash

################################################################################
#                                                                              #
#                       Simple Daily Backup Script                             #
#                                                                              #
################################################################################

#---------------------------- Read Conf File ---------------------------------#
source /etc/backup/backup.conf

#----------------------------- Backup Name -----------------------------------#
BACKUP_TODAY=Daily-$($DATE +%j)-$($DATE +%A);
BACKUP_YESTERDAY=*-$($DATE -d "yesterday" +%A);
BACKUP_LAST_WEEK=*-$($DATE +%A);

#---------------------------- Body of Script ---------------------------------#

# Ensure user is root
if (( `$ID -u` != 0 )); then 
    $ECHO "$0 must be run as root.";
    exit;
fi;

# Remove week-old backup, if one exists
if [ -d $MOUNT_POINT/$BACKUP_LAST_WEEK ] ; then
    $RM -rf $MOUNT_POINT/$BACKUP_LAST_WEEK ;
fi;

# Create directory for backup
$MKDIR $MOUNT_POINT/$BACKUP_TODAY ;

# Make a hard-link to yesterday's backup, if one exists
if [ -d $MOUNT_POINT/$BACKUP_YESTERDAY ] ; then
    $CP -al $MOUNT_POINT/$BACKUP_YESTERDAY/* $MOUNT_POINT/$BACKUP_TODAY ;
fi;

# rsync the system to the backup
for i in $FILE_SYSTEMS
do
$RSYNC                                       \
    -xav --delete                            \
    $i $MOUNT_POINT/$BACKUP_TODAY ;
done
