#! /bin/bash

################################################################################
#                                                                              #
#                       Simple weekly Backup Script                            #
#                                                                              #
################################################################################

#---------------------------- Read Conf File ---------------------------------#
source /etc/backup/backup.conf

#----------------------------- Backup Name -----------------------------------#
BACKUP_THIS_WEEK=Weekly-$($DATE +%V);
BACKUP_LAST_MONTH=*-$(( $($DATE +%V) - 4 ));
BACKUP_SUNDAY=*Sunday;

#---------------------------- Body of Script ---------------------------------#

# Ensure user is root
if (( `$ID -u` != 0 )); then
    $ECHO "$0 must be run as root.";
    exit;
fi;

# Remove month-old backup, if one exists
if [ -d $MOUNT_POINT/$BACKUP_LAST_MONTH ] ; then
    $RM -rf $MOUNT_POINT/$BACKUP_LAST_MONTH ;
fi;

# Create directory for backup
$MKDIR $MOUNT_POINT/$BACKUP_THIS_WEEK ;

# Make a hard-link to Sunday's backup, if one exists
# If no backup for Sunday exists, rsync the system to this week's backup
if [ -d $MOUNT_POINT/$BACKUP_SUNDAY ] ; then
    $CP -al $MOUNT_POINT/$BACKUP_SUNDAY/* $MOUNT_POINT/$BACKUP_THIS_WEEK ;
else
    for i in $FILE_SYSTEMS
    do
        $RSYNC                                       \
            -xav --delete                            \
            $i $MOUNT_POINT/$BACKUP_THIS_WEEK ;
    done
fi;
